// <auto-generated />
using System;
using CaseStudyCard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseStudyCard.Migrations
{
    [DbContext(typeof(CaseStudyCardContext))]
    [Migration("20190805130352_CardsShownFix")]
    partial class CardsShownFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaseStudyCard.Models.ApplicationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardsShown");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName");

                    b.Property<int>("Income");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationForm");
                });

            modelBuilder.Entity("CaseStudyCard.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("APR");

                    b.Property<string>("CardName");

                    b.Property<string>("ImageURL");

                    b.Property<int>("MaximumEarnings");

                    b.Property<int>("MinimumAge");

                    b.Property<int>("MinimumEarnings");

                    b.Property<string>("PromotionalMessage");

                    b.HasKey("Id");

                    b.ToTable("CreditCard");
                });
#pragma warning restore 612, 618
        }
    }
}
